'use client';
import { useEffect,useState } from 'react';
import Sidebar from '../../components/Sidebar';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000/api/v1';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('csrf_token='))?.split('=')[1]||''}
type N={id:string;type:string;title:string;body:string;actionUrl?:string;status:string;createdAt:string};
type Pref={appointmentReminders:boolean;taskReminders:boolean;consentReminders:boolean;invoiceReminders:boolean;emailEnabled:boolean;smsEnabled:boolean;reminderHoursBefore:number};
export default function NotificationsPage(){const [items,setItems]=useState<N[]>([]);const [pref,setPref]=useState<Pref|null>(null);const [message,setMessage]=useState('');
 async function load(){const [a,b]=await Promise.all([fetch(`${API}/notifications`,{credentials:'include'}),fetch(`${API}/notifications/preferences`,{credentials:'include'})]);if(!a.ok||!b.ok)throw new Error('No se pudieron cargar los recordatorios');setItems(await a.json());setPref(await b.json())}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 async function save(){if(!pref)return;const r=await fetch(`${API}/notifications/preferences`,{method:'PATCH',credentials:'include',headers:{'content-type':'application/json','x-csrf-token':csrf()},body:JSON.stringify(pref)});setMessage(r.ok?'Preferencias guardadas':'No se pudieron guardar')}
 async function mark(id:string){await fetch(`${API}/notifications/${id}/read`,{method:'PATCH',credentials:'include',headers:{'x-csrf-token':csrf()}});setItems(x=>x.map(n=>n.id===id?{...n,status:'READ'}:n))}
 async function process(){const r=await fetch(`${API}/notifications/process-due`,{method:'POST',credentials:'include',headers:{'x-csrf-token':csrf()}});const b=await r.json();setMessage(r.ok?`${b.created} recordatorios nuevos generados`:b.message||'No autorizado');if(r.ok)load()}
 return <div className="app-layout"><Sidebar/><main className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">COMUNICACIONES</p><h1>Notificaciones y recordatorios</h1><p className="dashboard-subtitle">Avisos operativos sin incluir notas clínicas ni diagnósticos.</p></div><button className="button" onClick={process}>Procesar pendientes</button></header>{message&&<p className="card">{message}</p>}
 <div className="grid"><section className="card"><h2>Bandeja</h2><div className="stack">{items.map(n=><article className="patient" key={n.id}><div><strong>{n.title}</strong><p className="muted">{n.body}</p><small>{new Date(n.createdAt).toLocaleString('es-ES')}</small></div>{n.status!=='READ'&&<button className="button secondary" onClick={()=>mark(n.id)}>Marcar leída</button>}</article>)}{!items.length&&<p className="muted">No hay notificaciones.</p>}</div></section>
 <section className="card"><h2>Preferencias</h2>{pref&&<div className="stack">{([['appointmentReminders','Citas'],['taskReminders','Tareas'],['consentReminders','Consentimientos'],['invoiceReminders','Facturas'],['emailEnabled','Correo electrónico'],['smsEnabled','SMS']] as const).map(([k,l])=><label className="patient" key={k}><span>{l}</span><input type="checkbox" checked={Boolean(pref[k])} onChange={e=>setPref({...pref,[k]:e.target.checked})}/></label>)}<label className="field">Horas de antelación<input type="number" min="1" max="168" value={pref.reminderHoursBefore} onChange={e=>setPref({...pref,reminderHoursBefore:Number(e.target.value)})}/></label><button className="button" onClick={save}>Guardar preferencias</button></div>}</section></div></main></div>}
