'use client';
import { FormEvent,useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import Sidebar from '@/components/Sidebar';
import { api } from '@/lib/api';
export default function PatientPortalAdminPage(){const {id}=useParams<{id:string}>();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function enable(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{await api(`/patients/${id}/portal-account`,{method:'POST',body:JSON.stringify({email,temporaryPassword:password})});setMessage('Acceso activado. Entrega la contraseña temporal al paciente por un canal seguro.');setPassword('')}catch(e){setError(e instanceof Error?e.message:'No se pudo activar')}finally{setBusy(false)}}
 async function disable(){if(!confirm('¿Desactivar el acceso del paciente al portal?'))return;setBusy(true);try{await api(`/patients/${id}/portal-account`,{method:'DELETE'});setMessage('Acceso desactivado.');setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo desactivar')}finally{setBusy(false)}}
 return <div className="app-layout"><Sidebar/><main className="patient-record-page"><Link href={`/patients/${id}`} className="patient-record-back">← Volver a la ficha</Link><header className="patient-record-header"><div><span className="eyebrow">Portal del paciente</span><h1>Gestionar acceso</h1><p>Activa o restablece el acceso sin exponer información clínica interna.</p></div></header>{error&&<div className="agenda-error">{error}</div>}{message&&<div className="patient-save-state">{message}</div>}<section className="patient-card"><form className="document-form" onSubmit={enable}><label><span>Correo de acceso</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label><span>Contraseña temporal</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/><small>Debe incluir mayúscula, minúscula y número.</small></label><div className="patient-record-actions"><button className="button primary" disabled={busy}>Activar o restablecer</button><button type="button" className="button secondary" onClick={disable} disabled={busy}>Desactivar acceso</button></div></form></section></main></div>}
