'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import Sidebar from '@/components/Sidebar';
import { api } from '@/lib/api';

type TaskStatus='DRAFT'|'PENDING'|'IN_PROGRESS'|'SUBMITTED'|'CHANGES_REQUESTED'|'COMPLETED'|'CANCELLED';
type Goal={id:string;title:string;status:string};
type Template={id:string;title:string;instructions?:string|null;category?:string|null};
type Task={id:string;title:string;instructions?:string|null;status:TaskStatus;dueDate?:string|null;patientFeedback?:string|null;clinicianNotes?:string|null;reviewComment?:string|null;submittedAt?:string|null;completedAt?:string|null;therapyGoal?:Goal|null;createdAt:string;updatedAt:string};
type Patient={id:string;firstName:string;lastName:string;status:string};
const LABEL:Record<TaskStatus,string>={DRAFT:'Borrador',PENDING:'Asignada',IN_PROGRESS:'En curso',SUBMITTED:'Entregada',CHANGES_REQUESTED:'Cambios solicitados',COMPLETED:'Completada',CANCELLED:'Cancelada'};
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'Sin fecha';

export default function PatientTasksPage(){
 const {id:patientId}=useParams<{id:string}>();
 const [patient,setPatient]=useState<Patient|null>(null),[tasks,setTasks]=useState<Task[]>([]),[goals,setGoals]=useState<Goal[]>([]),[templates,setTemplates]=useState<Template[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState<'ALL'|TaskStatus>('ALL');
 const [selectedTemplate,setSelectedTemplate]=useState('');
 async function load(){try{setLoading(true);setError('');const [p,t,g,tm]=await Promise.all([api<Patient>(`/patients/${patientId}`),api<Task[]>(`/patients/${patientId}/tasks`),api<Goal[]>(`/patients/${patientId}/goals`),api<Template[]>('/patients/task-templates/library')]);setPatient(p);setTasks(t);setGoals(g);setTemplates(tm);}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las tareas');}finally{setLoading(false)}}
 useEffect(()=>{load()},[patientId]);
 async function createTask(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);try{setSaving(true);await api(`/patients/${patientId}/tasks`,{method:'POST',body:JSON.stringify({title:fd.get('title'),instructions:fd.get('instructions')||undefined,dueDate:fd.get('dueDate')||undefined,therapyGoalId:fd.get('therapyGoalId')||undefined,saveAsDraft:fd.get('action')==='draft'})});form.reset();setSelectedTemplate('');await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo crear la tarea')}finally{setSaving(false)}}
 async function update(task:Task,payload:Record<string,unknown>){try{setError('');await api(`/patients/${patientId}/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify(payload)});await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo actualizar la tarea')}}
 async function removeDraft(task:Task){if(!confirm(`¿Eliminar el borrador “${task.title}”?`))return;try{await api(`/patients/${patientId}/tasks/${task.id}`,{method:'DELETE'});await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo eliminar')}}
 async function saveTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,fd=new FormData(f);try{await api('/patients/task-templates/library',{method:'POST',body:JSON.stringify({title:fd.get('title'),instructions:fd.get('instructions'),category:fd.get('category')})});f.reset();await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar la plantilla')}}
 const visible=useMemo(()=>filter==='ALL'?tasks:tasks.filter(t=>t.status===filter),[tasks,filter]);
 const pending=tasks.filter(t=>['PENDING','IN_PROGRESS','CHANGES_REQUESTED'].includes(t.status)).length,submitted=tasks.filter(t=>t.status==='SUBMITTED').length,completed=tasks.filter(t=>t.status==='COMPLETED').length;
 const selected=templates.find(t=>t.id===selectedTemplate);
 if(loading)return <div className="app-layout"><Sidebar/><main className="patient-tasks-page"><div className="patient-record-loading">Cargando flujo de tareas…</div></main></div>;
 if(!patient)return <div className="app-layout"><Sidebar/><main className="patient-tasks-page"><div className="agenda-error">{error||'Paciente no encontrado'}</div></main></div>;
 return <div className="app-layout"><Sidebar syncText="Trabajo entre sesiones"/><main className="patient-tasks-page">
  <header className="patient-plan-header"><div><Link href={`/patients/${patient.id}`} className="patient-record-back">← Volver a la ficha clínica</Link><div className="patient-record-kicker">Sprint 12 · Flujo completo</div><h1>Tareas de {patient.firstName} {patient.lastName}</h1><p>Asigna, recibe, revisa y cierra el trabajo terapéutico entre sesiones.</p></div></header>
  {error&&<div className="agenda-error">{error}</div>}
  <section className="therapy-overview-grid"><article><span>En trabajo</span><strong>{pending}</strong><small>Asignadas o en curso</small></article><article><span>Por revisar</span><strong>{submitted}</strong><small>Entregadas por el paciente</small></article><article><span>Completadas</span><strong>{completed}</strong><small>Revisadas por el profesional</small></article><article><span>Total</span><strong>{tasks.length}</strong><small>Incluye borradores y canceladas</small></article></section>
  <div className="patient-tasks-layout"><section className="patient-record-card"><div className="patient-plan-section-heading"><div><span>01</span><div><h2>Nueva tarea</h2><p>Usa una plantilla o redacta una indicación personalizada.</p></div></div></div>
   <form className="therapy-goal-form" onSubmit={createTask}><label><span>Plantilla</span><select value={selectedTemplate} onChange={e=>setSelectedTemplate(e.target.value)}><option value="">Tarea personalizada</option>{templates.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label><span>Título</span><input name="title" required minLength={2} maxLength={180} key={`title-${selectedTemplate}`} defaultValue={selected?.title||''}/></label><label><span>Instrucciones</span><textarea name="instructions" maxLength={5000} key={`instructions-${selectedTemplate}`} defaultValue={selected?.instructions||''}/></label><div className="task-form-row"><label><span>Fecha orientativa</span><input type="date" name="dueDate"/></label><label><span>Objetivo asociado</span><select name="therapyGoalId" defaultValue=""><option value="">Sin objetivo asociado</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label></div><div className="patient-record-actions"><button className="button secondary" name="action" value="draft" disabled={saving}>Guardar borrador</button><button className="button" name="action" value="assign" disabled={saving||patient.status==='ARCHIVED'}>{saving?'Guardando…':'Asignar al paciente'}</button></div></form>
  </section>
  <section className="patient-record-card"><div className="task-list-heading"><div><h2>Seguimiento</h2><p>El paciente entrega; el profesional valida el cierre.</p></div><div className="timeline-filters"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>Todas</button><button className={filter==='SUBMITTED'?'active':''} onClick={()=>setFilter('SUBMITTED')}>Por revisar</button><button className={filter==='IN_PROGRESS'?'active':''} onClick={()=>setFilter('IN_PROGRESS')}>En curso</button><button className={filter==='COMPLETED'?'active':''} onClick={()=>setFilter('COMPLETED')}>Completadas</button></div></div>
   <div className="therapeutic-task-list">{visible.map(task=><article key={task.id} className={`therapeutic-task-card task-${task.status.toLowerCase()}`}><div className="task-card-main"><div className="therapy-goal-top"><span className={`task-status task-status-${task.status.toLowerCase()}`}>{LABEL[task.status]}</span>{task.dueDate&&<span className="task-date">Fecha objetivo {fmt(task.dueDate)}</span>}{task.therapyGoal&&<span className="task-goal">{task.therapyGoal.title}</span>}</div><h3>{task.title}</h3>{task.instructions&&<p>{task.instructions}</p>}
   {task.patientFeedback&&<div className="patient-record-card"><strong>Respuesta del paciente</strong><p>{task.patientFeedback}</p>{task.submittedAt&&<small>Entregada {fmt(task.submittedAt)}</small>}</div>}
   {task.reviewComment&&<div className="patient-record-card"><strong>Devolución profesional</strong><p>{task.reviewComment}</p></div>}
   <label><span>Nota clínica privada</span><textarea defaultValue={task.clinicianNotes||''} onBlur={e=>{if(e.target.value!==(task.clinicianNotes||''))update(task,{clinicianNotes:e.target.value})}}/></label>
   {task.status==='SUBMITTED'&&<label><span>Devolución para el paciente</span><textarea id={`review-${task.id}`} defaultValue={task.reviewComment||''} placeholder="Feedback breve, claro y no punitivo…"/></label>}</div>
   <div className="therapy-goal-actions">{task.status==='DRAFT'&&<><button onClick={()=>update(task,{status:'PENDING'})}>Asignar</button><button className="danger" onClick={()=>removeDraft(task)}>Eliminar borrador</button></>}{task.status==='SUBMITTED'&&<><button onClick={()=>update(task,{status:'COMPLETED',reviewComment:(document.getElementById(`review-${task.id}`) as HTMLTextAreaElement)?.value||''})}>Completar tras revisión</button><button onClick={()=>update(task,{status:'CHANGES_REQUESTED',reviewComment:(document.getElementById(`review-${task.id}`) as HTMLTextAreaElement)?.value||''})}>Solicitar cambios</button></>}{task.status==='COMPLETED'&&<button onClick={()=>update(task,{status:'IN_PROGRESS'})}>Reabrir</button>}{!['DRAFT','COMPLETED','CANCELLED'].includes(task.status)&&<button onClick={()=>update(task,{status:'CANCELLED'})}>Cancelar</button>}</div></article>)}{visible.length===0&&<div className="therapy-empty"><strong>No hay tareas en esta vista</strong><p>Crea una tarea o cambia el filtro.</p></div>}</div>
  </section></div>
  <section className="patient-record-card"><div className="patient-plan-section-heading"><div><span>02</span><div><h2>Biblioteca de plantillas</h2><p>Guarda indicaciones reutilizables sin vincularlas a ningún paciente.</p></div></div></div><form className="therapy-goal-form" onSubmit={saveTemplate}><label><span>Nombre</span><input name="title" required minLength={2} maxLength={180}/></label><label><span>Instrucciones base</span><textarea name="instructions" maxLength={5000}/></label><div className="task-form-row"><label><span>Categoría</span><input name="category" maxLength={80} placeholder="Registro, exposición, psicoeducación…"/></label><button className="button secondary">Guardar plantilla</button></div></form></section>
 </main></div>
}
