const API=process.env.ASEPSICO_API_URL||'http://localhost:4000/api/v1';
const email=process.env.ASEPSICO_SMOKE_EMAIL||'demo@asepsico.es';
const password=process.env.ASEPSICO_SMOKE_PASSWORD||'AsePsico2026!';
const cookies=new Map();
function cookieHeader(){return [...cookies].map(([k,v])=>`${k}=${v}`).join('; ')}
function capture(res){const values=res.headers.getSetCookie?.()||[];for(const raw of values){const [pair]=raw.split(';');const i=pair.indexOf('=');cookies.set(pair.slice(0,i),pair.slice(i+1));}}
async function req(path,{method='GET',body}={}){const headers={};if(cookies.size)headers.cookie=cookieHeader();if(body!==undefined)headers['content-type']='application/json';if(!['GET','HEAD'].includes(method)){const csrf=cookies.get('csrf_token');if(csrf)headers['x-csrf-token']=decodeURIComponent(csrf)}const res=await fetch(API+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});capture(res);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(`${method} ${path}: ${res.status} ${JSON.stringify(data)}`);return data;}
function assert(value,message){if(!value)throw new Error(message)}
const stamp=Date.now();
console.log('1/9 Login');await req('/auth/login',{method:'POST',body:{email,password}});
console.log('2/9 Crear paciente');const patient=await req('/patients',{method:'POST',body:{firstName:'Prueba',lastName:`Usabilidad ${stamp}`,email:`smoke-${stamp}@example.test`,phone:'+34600000000'}});assert(patient.id,'No se devolvió patient.id');
console.log('3/9 Guardar y recargar historia');await req(`/patients/${patient.id}/history`,{method:'PATCH',body:{reasonForConsultation:'Prueba automática de persistencia'}});const history=await req(`/patients/${patient.id}/history`);assert(history.reasonForConsultation==='Prueba automática de persistencia','La historia no persistió');
console.log('4/9 Guardar objetivo y tarea');const goal=await req(`/patients/${patient.id}/goals`,{method:'POST',body:{title:'Objetivo smoke test',priority:2}});const task=await req(`/patients/${patient.id}/tasks`,{method:'POST',body:{title:'Tarea smoke test',therapyGoalId:goal.id}});const tasks=await req(`/patients/${patient.id}/tasks`);assert(tasks.some(x=>x.id===task.id),'La tarea no apareció al recargar');
console.log('5/9 Guardar escala');const assessment=await req(`/patients/${patient.id}/assessments`,{method:'POST',body:{scaleCode:'PHQ9',answers:[0,0,0,0,0,0,0,0,0]}});const assessments=await req(`/patients/${patient.id}/assessments`);assert(assessments.some(x=>x.id===assessment.id),'La escala no persistió');
console.log('6/9 Guardar documento, consentimiento e informe');await req(`/patients/${patient.id}/documents`,{method:'POST',body:{title:'Documento smoke',type:'ADMINISTRATIVE',fileName:'smoke.pdf',mimeType:'application/pdf',storageKey:`smoke/${stamp}`}});await req(`/patients/${patient.id}/consents`,{method:'POST',body:{title:'Consentimiento smoke',type:'DATA_PROCESSING',status:'PENDING'}});await req(`/patients/${patient.id}/reports`,{method:'POST',body:{title:'Informe smoke',type:'EVOLUTION',status:'DRAFT',content:'Contenido de comprobación automática.'}});assert((await req(`/patients/${patient.id}/documents`)).length>0,'Documento no persistió');assert((await req(`/patients/${patient.id}/consents`)).length>0,'Consentimiento no persistió');assert((await req(`/patients/${patient.id}/reports`)).length>0,'Informe no persistió');
console.log('7/9 Guardar preferencias');await req('/notifications/preferences',{method:'PATCH',body:{appointmentReminders:true,taskReminders:true,consentReminders:false,invoiceReminders:true,emailEnabled:false,smsEnabled:false,reminderHoursBefore:24}});const pref=await req('/notifications/preferences');assert(pref.reminderHoursBefore===24,'Preferencias no persistieron');
console.log('8/9 Comprobar timeline');const timeline=await req(`/patients/${patient.id}/timeline`);assert(Array.isArray(timeline),'Timeline no disponible');
console.log('9/9 Archivar paciente de prueba');await req(`/patients/${patient.id}`,{method:'DELETE'});
console.log('OK: flujo crítico guardado y recargado correctamente.');
