import { ForbiddenException, NotFoundException } from '@nestjs/common';
import { NotificationsService } from '../src/notifications/notifications.service';
const owner:any={sub:'o1',workspaceId:'w1',role:'OWNER'};
const therapist:any={sub:'t1',workspaceId:'w1',role:'THERAPIST'};
function mock(){return {notification:{findMany:jest.fn(),updateMany:jest.fn(),createMany:jest.fn()},notificationPreference:{findUnique:jest.fn(),findMany:jest.fn().mockResolvedValue([]),upsert:jest.fn()},patientPortalAccount:{findFirst:jest.fn()},patient:{findFirst:jest.fn()},session:{findMany:jest.fn()},therapeuticTask:{findMany:jest.fn()},consentRecord:{findMany:jest.fn()},invoice:{findMany:jest.fn()},auditLog:{create:jest.fn()}} as any}
describe('Notifications security and integration',()=>{
 it('scopes professional inbox to workspace and user',async()=>{const p=mock();p.notification.findMany.mockResolvedValue([]);await new NotificationsService(p).listProfessional(owner,true);expect(p.notification.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({workspaceId:'w1',userId:'o1',audience:'PROFESSIONAL'})}))});
 it('prevents reading another user notification',async()=>{const p=mock();p.notification.updateMany.mockResolvedValue({count:0});await expect(new NotificationsService(p).markProfessionalRead(owner,'foreign')).rejects.toBeInstanceOf(NotFoundException)});
 it('only owner/admin can process reminders',async()=>{const p=mock();await expect(new NotificationsService(p).processDue(therapist)).rejects.toBeInstanceOf(ForbiddenException);expect(p.session.findMany).not.toHaveBeenCalled()});
 it('uses idempotent dedupe keys and audits a batch',async()=>{const p=mock();p.session.findMany.mockResolvedValue([{id:'s1',patientId:'p1',therapistId:'t1',startsAt:new Date(),type:'INDIVIDUAL'}]);p.therapeuticTask.findMany.mockResolvedValue([]);p.consentRecord.findMany.mockResolvedValue([]);p.invoice.findMany.mockResolvedValue([]);p.notification.createMany.mockResolvedValue({count:2});await new NotificationsService(p).processDue(owner);expect(p.notification.createMany).toHaveBeenCalledWith(expect.objectContaining({skipDuplicates:true,data:expect.arrayContaining([expect.objectContaining({dedupeKey:'session:s1:patient:24h'}),expect.objectContaining({dedupeKey:'session:s1:therapist:24h'})])}));expect(p.auditLog.create).toHaveBeenCalled()});

 it('respects disabled patient reminder preferences',async()=>{const p=mock();const soon=new Date(Date.now()+60*60_000);p.session.findMany.mockResolvedValue([{id:'s1',patientId:'p1',therapistId:'t1',startsAt:soon,type:'INDIVIDUAL'}]);p.therapeuticTask.findMany.mockResolvedValue([]);p.consentRecord.findMany.mockResolvedValue([]);p.invoice.findMany.mockResolvedValue([]);p.notificationPreference.findMany.mockResolvedValue([{patientId:'p1',appointmentReminders:false,taskReminders:true,consentReminders:true,invoiceReminders:true,reminderHoursBefore:24},{userId:'t1',appointmentReminders:true,taskReminders:true,consentReminders:true,invoiceReminders:true,reminderHoursBefore:24}]);p.notification.createMany.mockResolvedValue({count:1});await new NotificationsService(p).processDue(owner);const rows=p.notification.createMany.mock.calls[0][0].data;expect(rows).toHaveLength(1);expect(rows[0]).toEqual(expect.objectContaining({audience:'PROFESSIONAL',userId:'t1'}));});
 it('portal query is scoped to patient and workspace',async()=>{const p=mock();p.patientPortalAccount.findFirst.mockResolvedValue({id:'pa1'});p.notification.findMany.mockResolvedValue([]);const portal={portalAccountId:'pa1',patientId:'p1',workspaceId:'w1'};await new NotificationsService(p).listPatient(portal);expect(p.notification.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({workspaceId:'w1',patientId:'p1',audience:'PATIENT'})}))});
});
